[package]
name = "zerucrypt"
version = "0.1.0"
authors = ["Ansho Rei <anshorei@zeroid.bit>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.23"
ripemd160 = "0.8"
secp256k1 = { version = "0.17", features = ["recovery", "rand"] }
base64 = "0.11"
rand = "0.7.3"
sha2 = "0.8"
basex-rs = "0.1"
