[package]
name = "zerucrypt"
version = "0.1.0"
authors = ["Ansho Rei <anshorei@zeroid.bit>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "*"
ripemd160 = "*"
secp256k1 = { version = "*", features = ["recovery", "rand"] }
base64 = "*"
rand = { version = "*", features = ["rand_os"] }
sha2 = "*"
basex-rs = "*"
